version: '3.0'
services:
  huang_cms:
    image: cms_api:1.0
    build: ./Demo3
    depends_on:
     - redis_huang
    ports:
     - "6020:6020"
    links:
     - redis_huang:redis_huang

  redis_huang:
    image: redis:latest
