version: '3.0'
services:
  cms_api:
    image: cms_api: 1.0
    build: ./Demo3
    depends_on:
     - redis
    ports:
     - "6020:6020"
    links:
     - "redis:redis"

  redis:
    image: redis:latest
